### ISSUE TITLE
找不到页面

### ISSUE THREAD

**Issue by msdx** [ttttmr/YoudaoNote-FirefoxAddons#1]
请问有其他安装方式吗？

**Comment by ttttmr** [comment]
啊，抱歉，发现插件被 Mozilla 停用了😂，在修的路上了

**Comment by ttttmr** [comment]
可以暂时以调试模式加载使用，clone本项目，进入文件夹中全选打个zip包，然后临时加载附加组件

**Comment by ttttmr** [comment]
有 pre-release 了，可以在这里临时加载 about:debugging#addons

**Comment by msdx** [comment]
@ttttmr 非常感谢您迁移的插件及对此问题的高效回复处理。

**Comment by ttttmr** [comment]
release可以直接安装了，Firefox审核还没过

**Comment by msdx** [comment]
好的，谢谢，已经成功安装及使用了。
